### PR TITLE
Allow match to be used as a Statement

### PR DESCRIPTION
**Pull request by jayphelps**
The `match` operator macro in most pattern-matching languages can be used as a statement. Currently, Sparkler returns an anonymous function expression, which is not a valid statement but can be used as one if simply wrapped in parentheses.

This lets us have syntax like so:

``` rust
var num = 1;
match num {
  0 => alert("zero"),
  1 => alert("one"),
  _ => alert("something else")
}
```

Which will become more useful since I'm working on adding more [Rust-like features](http://static.rust-lang.org/doc/master/tutorial.html#pattern-matching) like multiple patterns via pipe `0 | 1` and ranges `0..10`.

### CODE REVIEW

**Comment by jayphelps** [comment]
Actually, besides my test case being lame, this approach of wrapping the anonymous function is flawed since you can't use the branches to return from the current function scope.

``` rust
function isZeroOrOne(num) {
    match num {
      0 => return true,
      1 => return true,
      _ => return false;
    }
   // Didn't actually return
}
```

Obviously, the above example is better written in Sparkler as:

``` rust
function isZeroOrOne {
  0 => return true,
  1 => return true,
  _ => return false;
}
```

...it was just a contrived example.

If you think `match` as a statement is something you'd merge, I'll spend some more time to see how best to accomplish this.

**Comment by natefaubion** [comment]
Thanks! I'll accept this PR, but part of the caveat of having match in a statement position is that you can't use it like a normal control-structure, as you've highlighted. Because it desugars to an IIFE, you can't use things like `break`, `continue`, and `return`. My unconvincing justification is the cases are ES6 lambdas, so you should expect them to work like lambdas. Ultimately, I would love for `match` to work like a control structure in a statement position, and work like an IIFE in expression position, but sweet.js doesn't provide a way to make that distinction.

**Comment by jayphelps** [comment]
@natefaubion jinx! looks like we were both thinking the same thing. I'll take a look and see if we can accomplish this without too much runtime. Might not be possible.

**Comment by natefaubion** [comment]
I've thought about it quite a bit, and being a contributor to sweet.js, I'm fully aware of the current limitations. It's just not possible at the moment with what sweet.js gives us. Someday, though!

**Comment by natefaubion** [comment]
I'll add a note to the docs explaining the caveat.

**Comment by natefaubion** [comment]
FYI, the real answer to match statements are ES\* `do` expressions.

**Comment by jayphelps** [comment]
@natefaubion bummer, but good to know. Saves me the time!

**Comment by natefaubion** [comment]
@jayphelps wrt to alternates (`|`), I've thought about that one a lot too! The problem is you are forced to use a state machine. I don't really like the state machine approach for JS since it results in an explosion of code for any non-trivial patterns (write a few cases that trigger the backtracking compiler to see). If we weren't precompiling and people didn't have to see the result, I might not care. But if first impression means you get a hug jumble of switches, I don't think anyone would want to use it. You also need finer grained case analysis and merging. Right now, my ghetto method of stringly AST comparisons means I can only merge on whole argument patterns. I'm actually experimenting with a rewrite that lets me do finer grained analysis for all sub-tests (such as array and array length). Perhaps after that lands, and we get a smarter backtracking compiler, alternates will become more feasible.

**Comment by natefaubion** [comment]
On second thought, does Rust only allow literals in alternates? If that's the case, its certainly feasible.

**Comment by jayphelps** [comment]
@natefaubion nope, accepts a pattern of any type. http://static.rust-lang.org/doc/master/rust.html#match-expressions

**Comment by natefaubion** [comment]
Another options is to hoist the alternate tests into inner functions, where each return an array of bindings. That way you can do:

``` js
function test(a0) {
  function alt1(x) {
    ...
  }
  function alt2(x) {
    ...
  }
  var r1 = alt1(a0) || alt2(a0);
  if (r1) {
    var foo = r1[0];
    var bar = r1[0];
    ...
  }
}
```

**Comment by natefaubion** [comment]
FYI, in the future, please commit changes to `src/*` rather than `macros/*`. The macros dir is for the final assembled macro.

**Comment by jayphelps** [comment]
Wow I don't know how I missed that. Will do.

**Comment by natefaubion** [comment]
@jayphelps Just added a proper match statement form. Were you still wanting to help out with 'or' patterns? Its fairly straightforward, if a bit involved. I'd be happy to walk you through it if you are still up for it.

**Comment by jayphelps** [comment]
@natefaubion absolutely--though I had to pause my OSS time alloc to push a major work project out the door. Do you IRC? Wanna talk bout this and query you on the new statement syntax.

**Comment by natefaubion** [comment]
@jayphelps I'm usually available on the sweet.js channel.

**Pull request merged**
